### ISSUE TITLE
Limit the number of characters to be entered

### ISSUE THREAD

**Issue by chandramuralis** [salte-io/ng-currency#117]
### Description

Is there anyway can we limit the number of characters to be entered in the text box? For example, I don't want the user to type anything more than 5 digits like how  HTML 'maxlength' property restricts by not allowing to even type more than 5 digits. I know 'hardCap' is something for that, but the problem is it will round it to the 'max' property value.
### Expected outcome

  <input
                            type="text"
                            class="form-control"
                            ng-currency
                            min="0"
                            max="99999"
                            hard-cap="5"             
                            fraction="0"
                            ng-required="true"
                            autocomplete="off"
                            ng-model="salary">
</input>
With the above example, if the user types 12345678, text box will convert it in to 99999 on blur event.  What I'm looking for is, not even let them type more than 12345.

**Comment by nick-woodward** [comment]
Hey @chandramuralis!

From the sounds of it you effectively want `hard-cap` to revert to the old value rather then updating to the max-value.

I'm not opposed to this change since it seems like it would be a good addition to `hard-cap`.

What do you think @aguirrel?

**Comment by aguirrel** [comment]
@nick-woodward yes I think it would be great! Only thing I see is what happend with decimal separator (.).  If you want to type up to 5 characters 12345 would be ok, but when input is blur and then you focus again, you will get 12345.00 (getting 3 more characters).  If we set  8 characters we can type 12345678, getting again the first problem.

I think this option should work well with cents option, so you don't get decimal separator at all.  @chandramuralis could it work for you? Or decimal separator is a must for you?

Any other solution? :)

**Comment by nick-woodward** [comment]
Correct me if I'm wrong about the following @chandramuralis.

@aguirrel I believe he's suggesting the following:

* max is set to 99999.99
* User enters 15000.00
* User then enters 100000.00
* The number reverts back to 15000.00 (rather then 99999.99) since that was the last valid value

**Comment by chandramuralis** [comment]
@aguirrel I don't think decimal separator is mandatory for me. 

@nick-woodward, I assume your example is specifically for the values with Decimal separators. If so, you are right. Even if possible we should ignore the decimal's as part of the length. 
For Example 

- max is set to 99999.99
- User enters 15000.00
- User then tries to enter 100000.00, but after typing 10000, the control shouldn't allow him to type any number other than '.' and then it should allow to type two more digits as cents.

**Comment by nick-woodward** [comment]
Hmm, I don't think we were talking about the same thing. In my example the user was able to enter 100000.00, however after clicking off the field the number reverts to 15000.00

**Comment by nick-woodward** [comment]
`ng-currency` has officially entered **maintenance mode**. 

For more information please visit the following issue, #205.
