### ISSUE TITLE
Saving entered values to minor units

### ISSUE THREAD

**Issue by parky128** [salte-io/ng-currency#179]
Hi,

I have just started using this library and was wondering is there any control on how the model values are converted from major to minor units during data-binding?

So for example, say I enter in a value of 5.00 in the input, I would like that to be stored as 500 in the model.

I know I can just loop over my models and divide or multiple by 100 when needed (saving or retrieving), but I just wondered are there any options with this library that would allow me to do this?

Thanks

**Comment by nick-woodward** [comment]
Hey @parky128!

I totally get why you'd want this functionality to be centralized in `ng-currency`.

I like you're suggestion, if you get the chance feel free to submit a PR and I'll look at it!

### Proposed API

#### Binding

```html
<input type="text" model="yourModel" ng-currency fraction-to-integer="true" />
```

#### Settings Provider

```js
var app = angular.module('app', ['ng-currency']);

app.config(function(ngCurrencySettingsProvider) {
  // This would be defaulted to false to prevent a breaking change
  ngCurrencySettings.defaults.fractionToInteger = true;
});
```

**Comment by nick-woodward** [comment]
`ng-currency` has officially entered **maintenance mode**. 

For more information please visit the following issue, #205.
